
# config notes:
# this config exercises jacobi iteration.  If Magic model is excluded, it should converge in ~4
# cycles.  The Magic model's heavy influence will cause it to reach iteration limit (15)
# This model is kept small by chopping down years and regions.  The filtering of regions
# will generate warnings due to running jacobi with an incomplete region mapping.

[common]
mode = "integrated jacobi"

# Modules to run (requires module input sections below)
# note "all" *excludes* the demo Magic model, but it can be explicitly added back
models_to_run=['all']
#models_to_run=['all', 'magic']

common_data_path='input/electricity/properties'
residential_data_path='input/residential'
output_path='output'
scenario_name = "green_chicken"

# Temporal resolution (inter-annual)
# default = 24 representative (rep) days and 4 rep hours
# d8h12 = 8 rep days and 12 rep hours,  d4h24 = 4 rep days and 24 rep hours, or custom
temporal_resolution = "default"

# Temporal resolution (annual)
# list format, cannot be less than or greater than input data
aggregate_years=false
aggregate_start_year = 2023 # initial year to start aggregation from, iff aggregate_years is enabled, else ignored
summary_years = [2025, 2030] # evaluation years / aggregation summary years (if selected)

strict_validation=false


[natural_gas]

input_path = 'input/natural_gas'
# region_filter = ...  # commented out for no filter == all regions

[elec_config]
input_path='input/electricity/parameters'
region_filter = ['7', '8', '9']  # comment line out to disable filter for "all regions"
regional_exchange=true
capacity_expansion=false
expansion_learning_type='disabled'  # disabled/linear/nonlinear
reserve_margin_required=false
spinning_reserve_required=false
ramping_required=false
# Select the method for projecting future electricity demand (e.g., "annual" or "enduse")
# "annual" will scale the base year electricity demand by an annual scalar value
# "end_use" will scale the base year electricity demand by hourly end use demand profiles
load_scale_mode = "end_use"
